<a href="https://colab.research.google.com/github/Silima1/Machine_learning_emprestimos_-_rendas/blob/main/NO%C3%87%C3%95ES%20BASICAS%20DE%20PYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulação de variaveis 


In [ ]:
nome = input()
idade = input()
print(' Confirmado', nome, 'a tua idade eh', idade , ' anos de idade')


Silima
27
 Confirmado Silima a tua idade eh 27  anos de idade


In [ ]:
a = 3
b = 10
ph = a*b/100*100
if ph>=27:
  print("Deve iniciar a medicacao com urgencia", 'seu ph ', ph)
elif ph<= 27:
  print('Saudavel', 'seu ph ', ph)
elif ph==0:
    print('parar consumo de bebidas alcolicas', 'seu ph ', ph)
else:
  print('Deve eliminar o consumo do alcool', 'seu ph ', ph)


Deve iniciar a medicacao com urgencia seu ph  30.0


**MANIPULAÇÃO DE STRINGS**

In [ ]:
a = 'casaco'
print(a)

casaco


In [ ]:
maiusculas = a.upper() # conversao de minusculas para maiusculas
print(maiusculas)

CASACO


In [ ]:
minusculas = a.lower() # convertendo de maiusculas para minusculas
print(minusculas)

casaco


In [ ]:
inicial = a.capitalize() # Inicial maiuscula
print(inicial)

Casaco


In [ ]:
metade_da_palavra = a[0:3] # da posicao  0 ate a 2 
print(metade_da_palavra)

cas


In [ ]:
utltimas_letras = a[3:] # apenas seleciona do inidice atual ao final
print(utltimas_letras)

aco


In [ ]:
substituir = a.replace('aco', 'inha') # substituicao de aco com inha
print(substituir)

casinha


In [ ]:
c = a.replace('o', 'a') # substituir o por a
print(c)

casaca


In [ ]:
# Localiza a letra s
c.find('s')

2

In [ ]:
# visualizar o tamanho
e = ' casaco '
print(len(e))

8


In [ ]:
# remover espacos em branco
f = e.strip()
print(f)

casaco


In [ ]:
print(len(f))

6


In [ ]:
# Concatenar variaveis 
n1 = 650
n2 = 750
n3 = 1000

In [ ]:
from ast import Raise
print(f'o resultado  de {n1},  {n2} e {n3} sera igual a {n1*n2*n3*48*2250/2}' )

o resultado  de 650,  750 e 1000 sera igual a 26325000000000.0


In [ ]:
import math # Raizes
math.sqrt(49)

7.0

In [ ]:
# ARREDONDAMENTOS
casos_de_doencas = 134
numero_habitantes = 34598
casos_por_habitante = casos_de_doencas/numero_habitantes
print (casos_por_habitante)


0.003873056246025782


In [ ]:
round(casos_por_habitante, 6)

0.003873

In [ ]:
print(f' o numero de casos por habitantes e de {round(casos_por_habitante, 4)}')

 o numero de casos por habitantes e de 0.0039


In [ ]:
num1 = int(input('Digite o primeiro numero: '))
num2 = int(input('Digite o segundo numero: '))
print(f'O resultado desta adicao eh: {num1 + num2}')

Digite o primeiro numero: 34
Digite o segundo numero: 56
O resultado desta adicao eh: 90


In [ ]:
num1 = int(input('Digite o primeiro numero: '))
num2 = int(input('Digite o segundo numero: '))
print(f'o resultado da subtracao de {num1} e {num2} eh {num1 - num2}')

Digite o primeiro numero: 23
Digite o segundo numero: 25
o resultado da subtracao de 23 e 25 eh -2


In [ ]:
num1 = int(input('Digite o primeiro numero: '))
num2 = int(input('Digite o segundo numero: '))
print(f'o resultado da multiplicacao de {num1} e {num2} e {num1 * num2}')

Digite o primeiro numero: 56
Digite o segundo numero: 99
o resultado da multiplicacao de 56 e 99 e 5544


In [ ]:
num1 = int(input('Digite o primeiro numero: '))
num2 = int(input('Digite o segundo numero: '))
print(f'o resultado da divisao de {num1} e {num2} e {num1 / num2}')

Digite o primeiro numero: 890
Digite o segundo numero: 890
o resultado da divisao de 890 e 890 e 1.0


Calculo de velocidade distancia e quantidade de litros gastos sabendo que 1l equivale a 12 km

In [ ]:
tempo = float(input('Tempo: '))
velocidade = int(input('Velocidade media: '))
distancia = tempo*velocidade
QLkm = float(input('km por litro '))
litros_usados = distancia/QLkm 
print(f' O tempo gasto foi de {tempo}h \n A velocidade media foi de {velocidade}km/h \n e a distancia percorrida foi de {round(distancia,2)}km, \n contudo o combustivel usado foi de {round(litros_usados, 2,)} Litros')


Tempo: 9
Velocidade media: 65
km por litro 15
 O tempo gasto foi de 9.0h 
 A velocidade media foi de 65km/h 
 e a distancia percorrida foi de 585.0km, 
 contudo o combustivel usado foi de 39.0 Litros


### Vamos agora trabalhar com operadores logicos e relacionais

In [ ]:
a = True
b = False

In [ ]:
a and b

False

In [ ]:
a & b # corresponde ao AND

False

In [ ]:
a | b # corresponde ao OR

True

In [ ]:
a or b

True

In [ ]:
a == b

False

In [ ]:
a = 17
b = 18

In [ ]:
a & b == 17 # igualdade

False

In [ ]:
a + b/2 == 17.5

False

In [ ]:
c = a + b
c

35

In [ ]:
d = c/2
d

17.5

In [ ]:
d>=c

False

In [ ]:
d!=a # diferente

True

### Vamos agora trabalhar com operadores condicionais

In [ ]:
a = float(input('Nota do exame escrito candidato '))
b = float(input('Nota da entrevista do candidato '))
c = a + b
d = c/2

if d >= 17:
  print('Ganhou bolsa com nota ', d)
elif d >= 16:
  print('Aprovado, mas condicionado a vaga', d)
elif d < 16 and d >= 14:
  print('O canditado possui qualidade para ser solicitado posteriorimente! aguarde por favor', d)
elif d >= 13:
  print('Recomendamos-te as proximas candaturas', d)
else:
  print('Lamentamos não podemos avançar com a candidatura e recomendamos-te um curso profissional', d)

Nota do exame escrito candidato 16
Nota da entrevista do candidato 12
O canditado possui qualidade para ser solicitado posteriorimente! aguarde por favor 14.0


#### GESTAO DE IDADES

In [ ]:
idade = int(input('Digite a idade idade: '))
if idade >= 0 and idade <=12:
  print(f'É uma criança com {idade} anos de idade')
elif idade > 12 and idade <18:
  print(f' É um adolescente com {idade} anos de idade')
elif idade >=18:
  print(f' É um adulto com {idade} anos de idade')
else:
  print('valor invalido, digite valores positivos por favor')

Digite a idade idade: -2
valor invalido, digite valores positivos por favor


In [ ]:
#CALCULO DE 3 NOTAS PARA DEFINIR DISPENSA AO EXAME E APROVACAO OU REPROVACAO
nota1 = float(input('Nota de M1 '))
nota2 = float(input('Nota de M2 '))
nota3 = float(input('Nota de M3 '))
Media = (nota1 + nota2 + nota3) /3

if Media >= 0 and Media <= 4:
  print(f'REPROVADO com media {Media} valores')
elif Media >=6 and Media <= 6.5:
  exame = float(input('Digite a nota do exame: '))
  if exame >= 6:
    print(f'Aprovado com nota do exame {exame}')
  else:
    print('Reprovado ao exama com nota ', exame)
elif  Media >= 6.6:
  print(f'DISPENSADO com media {Media} valores')
else:
  print('Faltou ao exame', Media)


Nota de M1 19
Nota de M2 18
Nota de M3 15
DISPENSADO com media 17.333333333333332 valores


#ESTRUTURA DE REPETICAO FOR E WHILE

In [ ]:
print(1)
print(2)
print(3)
print(4)
print(5)

1
2
3
4
5


In [ ]:
for vqualquer in range(1, 7):
  print(vqualquer)

1
2
3
4
5
6


In [ ]:
for vqualquer in range(7, 0, -2):
  print(vqualquer)

7
5
3
1


In [ ]:
soma = 0
for i in range(1, 6): # vai sempre adicionando o valor da posicao seguinte
  soma = soma + i
  #print(soma) #valores parciais
print(soma) # soma global


15


In [ ]:
somado = ['Leonel, Silima, bla, bla']
for i in range(1, 10): # vai sempre adicionando o valor da posicao seguinte
  #soma = soma + i
  print(somado)
#print(somado) # soma global

['Leonel, Silima, bla, bla']
['Leonel, Silima, bla, bla']
['Leonel, Silima, bla, bla']
['Leonel, Silima, bla, bla']
['Leonel, Silima, bla, bla']
['Leonel, Silima, bla, bla']
['Leonel, Silima, bla, bla']
['Leonel, Silima, bla, bla']
['Leonel, Silima, bla, bla']


In [ ]:
myName = 'Leonel'
for nome in myName: # vai sempre adicionando o valor da posicao seguint
  if nome == 'l':
    print("Letra encontrada")



Letra encontrada


In [ ]:
for i in range(0, 5): # percorre todos os valores do for interno
  print(i)
  print('------')
  for j in range (0, 3):
    print(j)
  print()

0
------
0
1
2

1
------
0
1
2

2
------
0
1
2

3
------
0
1
2

4
------
0
1
2



#WHILE

In [ ]:
numero = 2
while numero < 10:
  print(numero)
  numero += 1
print('-----')

2
3
4
5
6
7
8
9
-----


In [ ]:
numero = 7
while numero > 2:
  print(numero)
  numero -= 1
print('-----')

7
6
5
4
3
-----


In [ ]:
1+2+3+4+5++6 # a seguir o exemplo com while

21

In [ ]:
soma = 0
numero = 1
while numero < 7:
  soma += numero
  numero +=1
print(soma)

21


In [ ]:
# validacao de numeros
numero = 5
numero = int(input("Digite teu mecanografico"))
while numero < 1 or numero >10:
  print("Sucedido com sucesso")
else:
  print("Tente novamente por favor")

Valor incorreto digite o valor valido


In [ ]:
# validacao de numeros
numero = 12
while numero < 1 or numero > 10:
  numero = int (input('Digite teu mecanografico '))

Digite teu mecanografico 14
Digite teu mecanografico 1


#Resolucao de exercicios com for e while


In [ ]:
nota = 0
for i in range(1, 6):
  nota = nota + i
  media = nota/5
print(f'A media eh {media}')


A media eh 3.0


In [ ]:
# Lendo 5 notas e imprimir a media
nota = media = soma =0
for _ in range(1,6):
  nota = float(input("DIgite a nota: "))
  soma += nota
print('A soma eh', soma)
media = soma/5
print('A media eh', media)

DIgite a nota: 12
DIgite a nota: 19
DIgite a nota: 20
DIgite a nota: 13
DIgite a nota: 15
A soma eh 79.0
A media eh 15.8


In [ ]:
numero = 1
somas = 0
while numero <= 5:
  nota = float(input('Nota '))
  somas += nota
  numero += 1
print('A media eh', somas/5)

Nota 15
Nota 16
Nota 17
Nota 15
Nota 13
A media eh 15.2


# TABUADA

In [ ]:
for i in range (1, 21):
  print('3 x {} = {}'.format(i, 3 * i))

3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30
3 x 11 = 33
3 x 12 = 36
3 x 13 = 39
3 x 14 = 42
3 x 15 = 45
3 x 16 = 48
3 x 17 = 51
3 x 18 = 54
3 x 19 = 57
3 x 20 = 60


In [ ]:
numero = 1
while numero <= 15:
  print('4 x {} = {}'.format(numero, 4 * numero))
  numero +=1 # incrementar para evitar loop

4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40
4 x 11 = 44
4 x 12 = 48
4 x 13 = 52
4 x 14 = 56
4 x 15 = 60


  # COLECOES
1.   TUPLAS
2.   LISTAS
1.   DICIONARIOS
2.   CONJUNTOS





In [ ]:
# TUPLAS
jogadores = ('Lionel', 'CR7', 'Mane', 'Ndembele')

In [ ]:
jogadores[0:4] # indices

('Lionel', 'CR7', 'Mane', 'Ndembele')

In [ ]:
jogadores.index('Lionel')

0

In [ ]:
for lista in jogadores:
  print(lista)

Lionel
CR7
Mane
Ndembele


In [ ]:
# LISTA
alunos_MIA = ['Ijip', 'Los', 'Hp', 'Miguel', 'Bruno']
prof_MIA = ['Ciro', 'Mario', 'Pedro']

In [ ]:
Lista_MIA = alunos_MIA + prof_MIA
Lista_MIA

['Ijip', 'Los', 'Hp', 'Miguel', 'Bruno', 'Ciro', 'Mario', 'Pedro']

In [ ]:
alunos_MIA.append('Leandro') # ADICIONAR ELEMENTO NA LISTA
alunos_MIA

['Ijip', 'Los', 'Hp', 'Miguel', 'Bruno', 'Unknow', 'Leandro']

In [ ]:
alunos_MIA.remove('Unknow') # REMOVER ELEMENTO DA LISTA
alunos_MIA

['Ijip', 'Los', 'Hp', 'Miguel', 'Bruno', 'Unknow']

In [ ]:
alunos_MIA.remove('Unknow')
alunos_MIA

['Ijip', 'Los', 'Hp', 'Miguel', 'Bruno', 'Leandro']

In [ ]:
del(Lista_MIA) # APAGAR A LISTA

In [ ]:
for i in alunos_MIA[0:5]:
  print(i)

Ijip
Los
Hp
Miguel
Bruno


# Dicionario

In [ ]:
ataques_por_empresas = {'DDoS': 100, 'worm': 24, 'rootkit': 30, 'trojan': 50}

In [ ]:
ataques_por_empresas['rootkit'] #consulta do dicionario

30

In [ ]:
ataques_por_empresas['Ransoware'] = 150 # ADICIONAR ELEMENTO NO DICIONARIO

In [ ]:
ataques_por_empresas['Ransoware']# CONSULTA

150

In [ ]:
ataques_por_empresas = {'DDoS': 100, 'worm': 24, 'rootkit': 30, 'trojan': 50, 'Ransoware':200} # refeito

In [ ]:
del(ataques_por_empresas)['worm'] # APAGAR ELEMENTO DA LISTA


In [ ]:
ataques_por_empresas

{'DDoS': 100, 'rootkit': 30, 'trojan': 50, 'Ransoware': 200}

In [ ]:
ataques_por_empresas.keys() # Palavras chaves do dicionario

dict_keys(['DDoS', 'worm', 'rootkit', 'trojan'])

In [ ]:
ataques_por_empresas.values() # valores do dicionario

dict_values([100, 24, 30, 50])

In [ ]:
ataques_por_empresas.items() # VISUALIZACAO DE DADOS NO FORMATO DE DICIONARIO

dict_items([('DDoS', 100), ('rootkit', 30), ('trojan', 50), ('Ransoware', 200)])

In [ ]:
outros_ataques = {'engenharia_social': 109, 'forca_bruta': 89}
outros_ataques 

{'engenharia_social': 109, 'forca_bruta': 89}

In [ ]:
ataques_por_empresas.update(outros_ataques) # PARA CONCATENAR DOIS DICIONARIOS
ataques_por_empresas

{'DDoS': 100,
 'rootkit': 30,
 'trojan': 50,
 'Ransoware': 200,
 'engenharia_social': 109,
 'forca_bruta': 89}

In [ ]:
ataques_por_empresas.values()

dict_values([100, 30, 50, 200, 109, 89])

In [ ]:
ataques_por_empresas['forca_bruta']

89

In [ ]:
# PERCORRER DICIONARIO COM FOR
for ataques, num_empresas in ataques_por_empresas.items(): # criar 2 variveis 1 para keys outra para values
  print(f'Ataques {ataques}, numero de empresas: {num_empresas}')

Ataques DDoS, numero de empresas: 100
Ataques rootkit, numero de empresas: 30
Ataques trojan, numero de empresas: 50
Ataques Ransoware, numero de empresas: 200
Ataques engenharia_social, numero de empresas: 109
Ataques forca_bruta, numero de empresas: 89


# CONJUNTOS

In [ ]:
Ciencias_computacao = ('Machine_learning','Machine_learning', 'Deep_learning','Deep_learning', 'Data_mining','Data_mining', 'computacao_quantica', 'Data_analisys')
Ciencias_computacao 

('Machine_learning',
 'Machine_learning',
 'Deep_learning',
 'Deep_learning',
 'Data_mining',
 'Data_mining',
 'computacao_quantica',
 'Data_analisys')

In [ ]:
print(set(Ciencias_computacao)) # Visualizar o conjunto sem repeticao de valores 'SET'

{'Data_mining', 'computacao_quantica', 'Deep_learning', 'Machine_learning', 'Data_analisys'}


In [ ]:
conj1 = {1, 2, 3, 4, 5, 6, 7}
conj2 = {4, 5, 13, 14, 15, 16, 17}
conj3 = conj1.intersection(conj2) # INTERCESSAO DE CONJUNTOS
conj3 


{4, 5}

In [ ]:
conj1 = {1, 2, 3, 4, 5, 6, 7}
conj2 = {4, 5, 13, 14, 15, 16, 17}
conj3 = conj1.difference(conj2) # DIFERENCA DE CONJUNTOS
conj3 

{1, 2, 3, 6, 7}

In [ ]:
conj3 = conj2.difference(conj1) # DIFERENCA DE CONJUNTOS
conj3 

{13, 14, 15, 16, 17}

# Matrizes
1. Para trabalhar com matriz precisamos importa a biblioteca numpy

In [3]:
import numpy as np

In [4]:
matriz = np.array([[2, 3, 6], [5, 8, 4]])  # UMA MATRIZ COM 2 LINHAS 3 COLUNAS
matriz

array([[2, 3, 6],
       [5, 8, 4]])

In [5]:
matriz.shape # PARA VERIFICAR O FORMATO DA MATRIZ 2 SAO LINHAS E 3 SAO COLUNAS 

(2, 3)

In [6]:
matriz[0]# indice 0 da linha

array([2, 3, 6])

In [7]:
matriz[1][0] # consulta de matriz elemento da linha 1 e coluna 0

5

In [11]:
matriz[0][0:2] # linha 0 coluna 0 a 1

array([2, 3])

In [26]:
# PERCORRER MATRIZ COM FOR 
for i in matriz[0]: # primeira linha da matriz
  print(i)

2
3
6


In [30]:
for i in range (matriz.shape[0]): # as 2 linhas da matriz
  print(matriz[i])

[2 3 6]
[5 8 4]


In [37]:
# PARA ACESSAR LINHAS E RESPETIVOS ELEMENTOS DE CADA COLUNAS
for i in range (matriz.shape[0]):
    print(matriz[i])
    for j in range(matriz.shape[1]):
      print(matriz[i][j])



[2 3 6]
2
3
6
[5 8 4]
5
8
4


# EXERCICIOS
1. LISTA
2. DICIONARIO
3. MATRIZ

In [76]:
Lista = []
for _ in range(1, 6):
  valor = int(input('Digite o valor:  '))
  Lista.append(valor)
  

Digite o valor:  16
Digite o valor:  3
Digite o valor:  3
Digite o valor:  17
Digite o valor:  19


In [79]:
Lista

[16, 3, 3, 17, 19]

In [90]:
soma = 0
for i in range(len(Lista)):
  soma += Lista[i]
  #print(Lista[1])
print('Soma: ', soma)


Soma:  58


In [93]:
np.array(Lista).sum() # somar uma lista com Numpy

58

In [113]:
# DICIONARIO
alunos = {}
for _ in range(1, 4):
  nome = input('Nome ')
  nota = float(input('Nota '))
  alunos[nome] = nota

Nome Leonel
Nota 19
Nome Ilidio
Nota 18.50
Nome Higinei
Nota 17.90


In [114]:
alunos

{'Leonel': 19.0, 'Ilidio': 18.5, 'Higinei': 17.9}

In [115]:
alunos.values()

dict_values([19.0, 18.5, 17.9])

In [159]:
soma = 0
for i in alunos.values():
  soma += nota
print('A media eh', soma/3)



A media eh 20.0


In [122]:
# MATRIZ
matriz = np.array([[10, 12, 15], [14, 13, 18]])
matriz

array([[10, 12, 15],
       [14, 13, 18]])

In [123]:
matriz.shape

(2, 3)

In [126]:
soma = 0
for i in range (matriz.shape[0]):
  for j in range(matriz.shape[1]):
    print(matriz[i][j])
    soma += matriz[i][j]
print('A soma da matriz eh', soma)

10
12
15
14
13
18
A soma da matriz eh 82


In [136]:
# CURIOSIDADE CRIANDO LISTA DE 4 ALUNOS 
lista = []
for _ in range(1, 5):
  nome = input('Nome ')
  lista.append(nome)

Nome Leonel
Nome Ilidio
Nome Higiney
Nome Bruno


In [143]:
# CURIOSIDADE CRIANDO UM DICIONARIO DE 15 ALUNOS E RESPETIVAS NOTAS
Estudantes_mia = {}
for _ in range(1,5):
  nome = input('Nome do aluno ')
  nota = float(input('Nota '))
  Estudantes_mia[nome] = nota

Nome do aluno Leonel
Nota 18
Nome do aluno Ilidio
Nota 16
Nome do aluno Higiney
Nota 16
Nome do aluno Bruno
Nota 20


In [144]:
Estudantes_mia

{'Leonel': 18.0, 'Ilidio': 16.0, 'Higiney': 16.0, 'Bruno': 20.0}

In [145]:
Estudantes_mia.values()

dict_values([18.0, 16.0, 16.0, 20.0])

In [163]:
soma = 0
for i in Estudantes_mia.values():
  soma += nota
  print(soma)
print('A media e ', soma/4)

20.0
40.0
60.0
80.0
A media e  20.0


In [178]:
MATRIZ = np.array([[2, 9, 4, 5], [21, 34,1,3], [1, 3,10,30]])
MATRIZ 

array([[ 2,  9,  4,  5],
       [21, 34,  1,  3],
       [ 1,  3, 10, 30]])

In [186]:
soma = 0
for i in range (MATRIZ.shape[0]):
  for y in range (MATRIZ.shape[1]):
    soma += MATRIZ[0][1] 
print(soma)

108
